GPU_ID: '0' 
model_restore: 'exp/logs/farside/checkpoint_20000' 

test_dir: exp/results/farside
dir_video: 'inputs/videos/farside' 
dir_mask: 'inputs/masks/farside'


img_shapes: [160, 360]
# img_shapes: [320, 600] -- for bmx-trees
coarse_only: False
use_refine: True
padding: 'SAME'
