GPU_ID: '0' 
model_restore: 'exp/logs/farside/checkpoint_130000' 

log_dir: exp/logs/farside_refine
dir_video: 'inputs/videos/farside' 
dir_mask: 'inputs/masks/farside'

# training
img_shapes: [160, 360]
batch_size: 5
lr: 0.00008

max_iters: 125000
max_epochs: 20000
print_iters: 200
summary_iters: 2000
model_iters: 10000


# Network
coarse_only: False
use_refine: True
padding: 'SAME'


# loss
stabilization_loss: True
ambiguity_loss: False
l1_loss: True
l1_loss_alpha: 1.
stabilization_loss_alpha: 0.3
ambiguity_loss_alpha: 0.1
